// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Based on mesa-v2021.09 (https://github.com/microchip-ung/mesa/) which has
// the following copyright and license:
//
// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This is an autogenerated file; do not edit by hand!
use derive_more::{From, Into};
/// PTP port configuration
///
/// Clock domain selection and mapping of ingress port number.
#[derive(Copy, Clone, Debug, Eq, PartialEq, From, Into)]
pub struct PTP_CFG(u32);
impl PTP_CFG {
    /// Selects the PTP time domain to use when updating receiveTimestamp in Delay_Resp frames.
    ///
    /// 0: Use time domain 0 1: Use time domain 1 2: Use time domain 2 3: Reserved.
    #[inline(always)]
    pub fn ptp_domain(&self) -> u32 {
        self.0 & 0x3
    }
    #[inline(always)]
    pub fn set_ptp_domain(&mut self, value: u32) {
        assert!(value <= 0x3);
        self.0 &= !0x3;
        self.0 |= value;
    }
    /// Part of portNumber used in portIdentity when ANA_ACL:PTP_DOM:PTP_SRC_PORT_CFG.PORT_NUM_SEL is set. PTP_PORT_NUM specifies bits 5:0 in portNumber. Remaining bits 15:6 in portNumber are taken from ANA_ACL:PTP_DOM:PTP_SRC_PORT_CFG.PORT_NUM
    #[inline(always)]
    pub fn ptp_port_num(&self) -> u32 {
        (self.0 & 0xfc) >> 2
    }
    #[inline(always)]
    pub fn set_ptp_port_num(&mut self, value: u32) {
        assert!(value <= 0x3f);
        let value = value << 2;
        self.0 &= !0xfc;
        self.0 |= value;
    }
}
/// VCAP_IS2 key selection
///
/// Key selection for VCAP_IS2 lookups. Replicated per lookup.
#[derive(Copy, Clone, Debug, Eq, PartialEq, From, Into)]
pub struct VCAP_S2_KEY_SEL(u32);
impl VCAP_S2_KEY_SEL {
    /// Applies to ARP/RARP frames.
    ///
    /// 0: Match against MAC_ETYPE entries. 1: Match against ARP entries.
    #[inline(always)]
    pub fn arp_key_sel(&self) -> u32 {
        self.0 & 0x1
    }
    #[inline(always)]
    pub fn set_arp_key_sel(&mut self, value: u32) {
        assert!(value <= 0x1);
        self.0 &= !0x1;
        self.0 |= value;
    }
    /// Applies to IPv4 multicast frames.
    ///
    /// 0: Match against MAC_ETYPE entries. 1: Match against IP4_TCP_UDP for IPv4 TCP/UDP frames and against IP4_OTHER entries for other IPv4 frames. 2: Match against IP_7TUPLE entries. 3: Match against IP4_VID entries.
    #[inline(always)]
    pub fn ip4_mc_key_sel(&self) -> u32 {
        (self.0 & 0xc0) >> 6
    }
    #[inline(always)]
    pub fn set_ip4_mc_key_sel(&mut self, value: u32) {
        assert!(value <= 0x3);
        let value = value << 6;
        self.0 &= !0xc0;
        self.0 |= value;
    }
    /// Applies to IPv4 unicast frames.
    ///
    /// 0: Match against MAC_ETYPE entries. 1: Match against IP4_TCP_UDP for IPv4 TCP/UDP frames and against IP4_OTHER entries for other IPv4 frames. 2: Match against IP_7TUPLE entries.
    #[inline(always)]
    pub fn ip4_uc_key_sel(&self) -> u32 {
        (self.0 & 0x30) >> 4
    }
    #[inline(always)]
    pub fn set_ip4_uc_key_sel(&mut self, value: u32) {
        assert!(value <= 0x3);
        let value = value << 4;
        self.0 &= !0x30;
        self.0 |= value;
    }
    /// Applies to IPv6 multicast frames.
    ///
    /// 0: Match against MAC_ETYPE entries. 1: Match against IP_7TUPLE entries. 2: Match against IP6_VID entries.
    #[inline(always)]
    pub fn ip6_mc_key_sel(&self) -> u32 {
        (self.0 & 0xc) >> 2
    }
    #[inline(always)]
    pub fn set_ip6_mc_key_sel(&mut self, value: u32) {
        assert!(value <= 0x3);
        let value = value << 2;
        self.0 &= !0xc;
        self.0 |= value;
    }
    /// Applies to IPv6 unicast frames.
    ///
    /// 0: Match against MAC_ETYPE entries. 1: Match against IP_7TUPLE entries.
    #[inline(always)]
    pub fn ip6_uc_key_sel(&self) -> u32 {
        (self.0 & 0x2) >> 1
    }
    #[inline(always)]
    pub fn set_ip6_uc_key_sel(&mut self, value: u32) {
        assert!(value <= 0x1);
        let value = value << 1;
        self.0 &= !0x2;
        self.0 |= value;
    }
    /// Applies to frames where frame_type is set to non Ethernet (CW or MPLS).
    ///
    /// 0: Match against MAC_ETYPE entries. 1: match against CUSTOM_1 entries. 2: match against CUSTOM_2 entries. 3: No lookup.
    #[inline(always)]
    pub fn non_eth_key_sel(&self) -> u32 {
        (self.0 & 0x300) >> 8
    }
    #[inline(always)]
    pub fn set_non_eth_key_sel(&mut self, value: u32) {
        assert!(value <= 0x3);
        let value = value << 8;
        self.0 &= !0x300;
        self.0 |= value;
    }
}
