// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Based on mesa-v2021.09 (https://github.com/microchip-ung/mesa/) which has
// the following copyright and license:
//
// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This is an autogenerated file; do not edit by hand!
use derive_more::{From, Into};
/// VS AN config 0
#[derive(From, Into)]
pub struct AN_CFG0(u32);
impl AN_CFG0 {
    /// Clear ABILITY_DETECT state counter
    pub fn abdet_clr(&self) -> u32 {
        (self.0 & 0x40) >> 6
    }
    pub fn set_abdet_clr(&mut self, value: u32) {
        let value = value << 6;
        assert!(value <= 0x40);
        self.0 &= !0x40;
        self.0 |= value;
    }
    /// Clear AN state machine history
    pub fn an_sm_hist_clr(&self) -> u32 {
        (self.0 & 0x20) >> 5
    }
    pub fn set_an_sm_hist_clr(&mut self, value: u32) {
        let value = value << 5;
        assert!(value <= 0x20);
        self.0 &= !0x20;
        self.0 |= value;
    }
    /// Disable clock gating
    pub fn clkg_disable(&self) -> u32 {
        (self.0 & 0x10) >> 4
    }
    pub fn set_clkg_disable(&mut self, value: u32) {
        let value = value << 4;
        assert!(value <= 0x10);
        self.0 &= !0x10;
        self.0 |= value;
    }
    /// Select source of 10G sync signal

    ///

    /// 0: KR internal 1: External
    pub fn sync10g_sel(&self) -> u32 {
        (self.0 & 0x4) >> 2
    }
    pub fn set_sync10g_sel(&mut self, value: u32) {
        let value = value << 2;
        assert!(value <= 0x4);
        self.0 &= !0x4;
        self.0 |= value;
    }
    /// Select source of 3G and 1G sync signal

    ///

    /// 0: KR internal 1: External
    pub fn sync8b10b_sel(&self) -> u32 {
        (self.0 & 0x2) >> 1
    }
    pub fn set_sync8b10b_sel(&mut self, value: u32) {
        let value = value << 1;
        assert!(value <= 0x2);
        self.0 &= !0x2;
        self.0 |= value;
    }
    /// Bypass training if 10G negotiated
    pub fn tr_disable(&self) -> u32 {
        (self.0 & 0x8) >> 3
    }
    pub fn set_tr_disable(&mut self, value: u32) {
        let value = value << 3;
        assert!(value <= 0x8);
        self.0 &= !0x8;
        self.0 |= value;
    }
}
/// VS AN break_link timer lsw
#[derive(From, Into)]
pub struct BL_LSW(u32);
impl BL_LSW {
    /// break_link_timer setting
    pub fn bl_tmr_lsw(&self) -> u32 {
        self.0 & 0xffff
    }
    pub fn set_bl_tmr_lsw(&mut self, value: u32) {
        assert!(value <= 0xffff);
        self.0 &= !0xffff;
        self.0 |= value;
    }
}
