// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Based on mesa-v2021.09 (https://github.com/microchip-ung/mesa/) which has
// the following copyright and license:
//
// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This is an autogenerated file; do not edit by hand!
use derive_more::{From, Into};

/// Register `PLL5G_BIST_CFG0A`
///
/// PLL5G BIST Configuration register 0A
///
/// Configuration register 0A for PLL5G BIST.
#[derive(From, Into)]
pub struct PLL5G_BIST_CFG0A(u32);
impl PLL5G_BIST_CFG0A {    ///
    /// BIST compare pre divider M
    pub fn pllb_div_factor_pre(&self) -> u32 {
        (self.0 & 0xffff) >> 0
    }
    pub fn set_pllb_div_factor_pre(&mut self, value: u32) {
        let value = value << 0;
        assert!(value <= 0xffff);
        self.0 &= !0xffff;
        self.0 |= value;
    }
}

/// Register `PLL5G_BIST_CFG0B`
///
/// PLL5G BIST Configuration register 0B
///
/// Configuration register 0B for PLL5G BIST.
#[derive(From, Into)]
pub struct PLL5G_BIST_CFG0B(u32);
impl PLL5G_BIST_CFG0B {    ///
    /// BIST compare divider repeat count
    pub fn pllb_lock_repeat(&self) -> u32 {
        (self.0 & 0xf0) >> 4
    }
    pub fn set_pllb_lock_repeat(&mut self, value: u32) {
        let value = value << 4;
        assert!(value <= 0xf0);
        self.0 &= !0xf0;
        self.0 |= value;
    }    ///
    /// BIST compare divider phase uncertainty
    pub fn pllb_lock_uncert(&self) -> u32 {
        (self.0 & 0xf) >> 0
    }
    pub fn set_pllb_lock_uncert(&mut self, value: u32) {
        let value = value << 0;
        assert!(value <= 0xf);
        self.0 &= !0xf;
        self.0 |= value;
    }    ///
    /// BIST measure mode, 0: frequency, 1: phase
    pub fn pllb_meas_mode(&self) -> u32 {
        (self.0 & 0x4000) >> 14
    }
    pub fn set_pllb_meas_mode(&mut self, value: u32) {
        let value = value << 14;
        assert!(value <= 0x4000);
        self.0 &= !0x4000;
        self.0 |= value;
    }    ///
    /// BIST start, 0: reset BIST, 1: start/enable BIST
    pub fn pllb_start_bist(&self) -> u32 {
        (self.0 & 0x8000) >> 15
    }
    pub fn set_pllb_start_bist(&mut self, value: u32) {
        let value = value << 15;
        assert!(value <= 0x8000);
        self.0 &= !0x8000;
        self.0 |= value;
    }
}

/// Register `PLL5G_BIST_CFG1`
///
/// PLL5G BIST Configuration register 1
///
/// Configuration register 1 for PLL5G BIST.
#[derive(From, Into)]
pub struct PLL5G_BIST_CFG1(u32);
impl PLL5G_BIST_CFG1 {    ///
    /// BIST compare divider M
    pub fn pllb_div_factor_m(&self) -> u32 {
        (self.0 & 0xffff) >> 0
    }
    pub fn set_pllb_div_factor_m(&mut self, value: u32) {
        let value = value << 0;
        assert!(value <= 0xffff);
        self.0 &= !0xffff;
        self.0 |= value;
    }
}

/// Register `PLL5G_STATUS1`
///
/// PLL5G Status 1
///
/// Status register 1 for the PLL5G
#[derive(From, Into)]
pub struct PLL5G_STATUS1(u32);
impl PLL5G_STATUS1 {    ///
    /// VCO frequency difference to refclk
    pub fn fbcnt_dif(&self) -> u32 {
        (self.0 & 0x3ff0) >> 4
    }
    pub fn set_fbcnt_dif(&mut self, value: u32) {
        let value = value << 4;
        assert!(value <= 0x3ff0);
        self.0 &= !0x3ff0;
        self.0 |= value;
    }    ///
    /// startup FSM lock status
    pub fn fsm_lock(&self) -> u32 {
        (self.0 & 0x1) >> 0
    }
    pub fn set_fsm_lock(&mut self, value: u32) {
        let value = value << 0;
        assert!(value <= 0x1);
        self.0 &= !0x1;
        self.0 |= value;
    }    ///
    /// startup FSM internal status
    pub fn fsm_stat(&self) -> u32 {
        (self.0 & 0xe) >> 1
    }
    pub fn set_fsm_stat(&mut self, value: u32) {
        let value = value << 1;
        assert!(value <= 0xe);
        self.0 &= !0xe;
        self.0 |= value;
    }    ///
    /// VCO frequency step stop
    pub fn gain_stat(&self) -> u32 {
        (self.0 & 0x7c000) >> 14
    }
    pub fn set_gain_stat(&mut self, value: u32) {
        let value = value << 14;
        assert!(value <= 0x7c000);
        self.0 &= !0x7c000;
        self.0 |= value;
    }    ///
    /// sigma delta ADC output
    pub fn sig_del(&self) -> u32 {
        (self.0 & 0x7f80000) >> 19
    }
    pub fn set_sig_del(&mut self, value: u32) {
        let value = value << 19;
        assert!(value <= 0x7f80000);
        self.0 &= !0x7f80000;
        self.0 |= value;
    }
}
