[package]
name = "vsc7448-pac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.derive_more]
version = "0.99.0"
default-features = false
features = ["from", "into"]
