// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Based on mesa-v2021.09 (https://github.com/microchip-ung/mesa/) which has
// the following copyright and license:
//
// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This is an autogenerated file; do not edit by hand!
use derive_more::{From, Into};
/// Frame pointer for TTI
#[derive(Copy, Clone, Debug, Eq, PartialEq, From, Into)]
pub struct TTI_FRM(u32);
impl TTI_FRM {
    /// Pointer to the frame in Frame Table, which TTI shall inject.
    #[inline(always)]
    pub fn frm_ptr(&self) -> u32 {
        self.0 & 0xfff
    }
    #[inline(always)]
    pub fn set_frm_ptr(&mut self, value: u32) {
        debug_assert!(value <= 0xfff);
        self.0 &= !0xfff;
        self.0 |= value;
    }
}
/// Miscellaneous TTI parameters
#[derive(Copy, Clone, Debug, Eq, PartialEq, From, Into)]
pub struct TTI_MISC_CFG(u32);
impl TTI_MISC_CFG {
    /// Enable counting of injected frames in AFI:TTI_MISC:TTI_INJ_CNT.TTI_INJ_CNT.
    #[inline(always)]
    pub fn inj_cnt_ena(&self) -> u32 {
        self.0 & 0x1
    }
    #[inline(always)]
    pub fn set_inj_cnt_ena(&mut self, value: u32) {
        debug_assert!(value <= 0x1);
        self.0 &= !0x1;
        self.0 |= value;
    }
}
/// Port and queue for injected frames.
#[derive(Copy, Clone, Debug, Eq, PartialEq, From, Into)]
pub struct TTI_PORT_QU(u32);
impl TTI_PORT_QU {
    /// Port number which injection queue transmits on. Injection queue is selected by QU_NUM. PORT_NUM must not be changed when timer is enabled.
    #[inline(always)]
    pub fn port_num(&self) -> u32 {
        self.0 & 0x3f
    }
    #[inline(always)]
    pub fn set_port_num(&mut self, value: u32) {
        debug_assert!(value <= 0x3f);
        self.0 &= !0x3f;
        self.0 |= value;
    }
    /// QU_NUM selects the queue, which the frame is injected into. For details, refer to the functional description of the queue system in the datasheet. QU_NUM must not be changed when timer is enabled.
    #[inline(always)]
    pub fn qu_num(&self) -> u32 {
        (self.0 & 0xffff00) >> 8
    }
    #[inline(always)]
    pub fn set_qu_num(&mut self, value: u32) {
        debug_assert!(value <= 0xffff);
        let value = value << 8;
        self.0 &= !0xffff00;
        self.0 |= value;
    }
}
/// Current state of TTI's tick counter
#[derive(Copy, Clone, Debug, Eq, PartialEq, From, Into)]
pub struct TTI_TICKS(u32);
impl TTI_TICKS {
    /// Ticks era value last time TTI was processed.
    #[inline(always)]
    pub fn last_tick_era(&self) -> u32 {
        (self.0 & 0x10000) >> 16
    }
    #[inline(always)]
    pub fn set_last_tick_era(&mut self, value: u32) {
        debug_assert!(value <= 0x1);
        let value = value << 16;
        self.0 &= !0x10000;
        self.0 |= value;
    }
    /// Number of ticks until next injection. Frame is injected when TICK_CNT=0. Upon injection TICK_CNT gets set to TIMER_LEN. Should be set to a random value in range 1-TIMER_LEN before starting TTI.
    #[inline(always)]
    pub fn tick_cnt(&self) -> u32 {
        self.0 & 0x1ff
    }
    #[inline(always)]
    pub fn set_tick_cnt(&mut self, value: u32) {
        debug_assert!(value <= 0x1ff);
        self.0 &= !0x1ff;
        self.0 |= value;
    }
}
/// TTI Timer configuration
#[derive(Copy, Clone, Debug, Eq, PartialEq, From, Into)]
pub struct TTI_TIMER(u32);
impl TTI_TIMER {
    /// Configuration of injection time jitter for TTI.
    ///
    /// 0: No jitter 1: Timer is set to a random value in the range [TIMER_LEN*0.75; TIMER_LEN] 2: Timer is set to a random value in the range [TIMER_LEN*0.50; TIMER_LEN] 3: Timer is set to a random value in the range [1;TIMER_LEN]
    #[inline(always)]
    pub fn jitter(&self) -> u32 {
        (self.0 & 0x30) >> 4
    }
    #[inline(always)]
    pub fn set_jitter(&mut self, value: u32) {
        debug_assert!(value <= 0x3);
        let value = value << 4;
        self.0 &= !0x30;
        self.0 |= value;
    }
    /// Timer Tick, which TTI shall use.
    #[inline(always)]
    pub fn tick_idx(&self) -> u32 {
        self.0 & 0x7
    }
    #[inline(always)]
    pub fn set_tick_idx(&mut self, value: u32) {
        debug_assert!(value <= 0x7);
        self.0 &= !0x7;
        self.0 |= value;
    }
    /// Enable timer. Note that disabling a timer can also be achieved by setting TIMER_LEN to 0. Before enabling a timer AFI::MISC_CTRL.AFI_ENA must be set to 1.
    #[inline(always)]
    pub fn timer_ena(&self) -> u32 {
        (self.0 & 0x40) >> 6
    }
    #[inline(always)]
    pub fn set_timer_ena(&mut self, value: u32) {
        debug_assert!(value <= 0x1);
        let value = value << 6;
        self.0 &= !0x40;
        self.0 |= value;
    }
    /// Number of ticks of configured TICK_IDX between frame injections. The period between each injection becomes tick_period x TIMER_LEN Setting TIMER_LEN to non-zero value enables TTI. 0x1FF (= Inject ASAP) is intended for removal of frame from buffer memory. Upon injection, HW sets TIMER_LEN to 0 (=Disable). Before setting TIMER_LEN, TICK_CNT should be set to a random value in range 1-TIMER_LEN (unless a specific initial timer value is desirable).
    ///
    /// 0 => Disable TTI. 1 => 1 tick 2 => 2 ticks ... 0x1ff => Inject ASAP, then set to TIMER_LEN=0 by AFI.
    #[inline(always)]
    pub fn timer_len(&self) -> u32 {
        (self.0 & 0x1ff0000) >> 16
    }
    #[inline(always)]
    pub fn set_timer_len(&mut self, value: u32) {
        debug_assert!(value <= 0x1ff);
        let value = value << 16;
        self.0 &= !0x1ff0000;
        self.0 |= value;
    }
}
/// TUPE Control
///
/// Control value for Table UPdate Engine (TUPE). See AFI:TUPE.
#[derive(Copy, Clone, Debug, Eq, PartialEq, From, Into)]
pub struct TTI_TUPE_CTRL(u32);
impl TTI_TUPE_CTRL {
    /// Control value for Table UPdate Engine (TUPE). See AFI:TUPE.
    #[inline(always)]
    pub fn tupe_ctrl(&self) -> u32 {
        self.0 & 0xff
    }
    #[inline(always)]
    pub fn set_tupe_ctrl(&mut self, value: u32) {
        debug_assert!(value <= 0xff);
        self.0 &= !0xff;
        self.0 |= value;
    }
}
