// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Based on mesa-v2021.09 (https://github.com/microchip-ung/mesa/) which has
// the following copyright and license:
//
// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This is an autogenerated file; do not edit by hand!

use crate::types::RegisterAddress;

// Register groups are stored in the tree as submodules

pub mod aggr;
pub mod coremem;
pub mod glag;
pub mod mirror_probe;
pub mod pgid;
pub mod ps_common;
pub mod ps_sticky;
pub mod ps_sticky_mask;
pub mod ram_ctrl;
pub mod sflow;
pub mod src;
pub mod stat_cnt_cfg_acl;
pub mod stat_cnt_cfg_bdlb;
pub mod stat_cnt_cfg_bum;
pub mod stat_cnt_cfg_erleg;
pub mod stat_cnt_cfg_irleg;
pub mod stat_cnt_cfg_isdx;
pub mod stat_cnt_cfg_port;
pub mod stat_cnt_cfg_queue;
pub mod stat_global_cfg_acl;
pub mod stat_global_cfg_bdlb;
pub mod stat_global_cfg_bum;
pub mod stat_global_cfg_erleg;
pub mod stat_global_cfg_irleg;
pub mod stat_global_cfg_isdx;
pub mod stat_global_cfg_port;
pub mod stat_global_cfg_queue;
pub mod upsid;

/// Aggregation port masks
pub struct AGGR(pub(super) u32);
impl AGGR {
    pub fn AGGR_CFG(&self) -> RegisterAddress<aggr::AGGR_CFG> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn PROBE_PORT_CFG1(&self) -> RegisterAddress<aggr::PROBE_PORT_CFG1> {
        RegisterAddress::new(self.0 + 0x8)
    }
}

/// Access core memory
pub struct COREMEM(pub(super) u32);
impl COREMEM {
    pub fn CM_ADDR(&self) -> RegisterAddress<coremem::CM_ADDR> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn RAM_INIT(&self) -> RegisterAddress<coremem::RAM_INIT> {
        RegisterAddress::new(self.0 + 0x0)
    }
}

/// Configuration for Global Link Aggregation Groups
pub struct GLAG(pub(super) u32);
impl GLAG {
    pub fn UPSID_CFG1(&self) -> RegisterAddress<glag::UPSID_CFG1> {
        RegisterAddress::new(self.0 + 0x8)
    }
}

/// Mirror probe configuration
pub struct MIRROR_PROBE(pub(super) u32);
impl MIRROR_PROBE {
    pub fn PROBE_CFG(&self) -> RegisterAddress<mirror_probe::PROBE_CFG> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn PROBE_PORT_CFG(&self) -> RegisterAddress<mirror_probe::PROBE_PORT_CFG> {
        RegisterAddress::new(self.0 + 0x4)
    }
    pub fn PS_DBG_CTRL(&self) -> RegisterAddress<mirror_probe::PS_DBG_CTRL> {
        RegisterAddress::new(self.0 + 0x110)
    }
}

/// Port group ID table configurations
pub struct PGID(pub(super) u32);
impl PGID {
    pub fn MBR_CNT_CFG(&self) -> RegisterAddress<pgid::MBR_CNT_CFG> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn PGID_CFG(&self) -> RegisterAddress<pgid::PGID_CFG> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn PGID_CFG1(&self) -> RegisterAddress<pgid::PGID_CFG1> {
        RegisterAddress::new(self.0 + 0x4)
    }
}

/// Common configurations for all ports
pub struct PS_COMMON(pub(super) u32);
impl PS_COMMON {
    pub fn CM_DATA(&self) -> RegisterAddress<ps_common::CM_DATA> {
        RegisterAddress::new(self.0 + 0x4)
    }
    pub fn COMMON_EQUAL_STACK_LINK_TTL_CFG(&self) -> RegisterAddress<ps_common::COMMON_EQUAL_STACK_LINK_TTL_CFG> {
        RegisterAddress::new(self.0 + 0x2c)
    }
    pub fn COMMON_VSTAX_CFG(&self) -> RegisterAddress<ps_common::COMMON_VSTAX_CFG> {
        RegisterAddress::new(self.0 + 0x28)
    }
    pub fn CPU_CFG(&self) -> RegisterAddress<ps_common::CPU_CFG> {
        RegisterAddress::new(self.0 + 0x10c)
    }
    pub fn MISC_CTRL(&self) -> RegisterAddress<ps_common::MISC_CTRL> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn PHYS_SRC_AGGR_CFG(&self) -> RegisterAddress<ps_common::PHYS_SRC_AGGR_CFG> {
        RegisterAddress::new(self.0 + 0x10)
    }
    pub fn PHYS_SRC_AGGR_CFG1(&self) -> RegisterAddress<ps_common::PHYS_SRC_AGGR_CFG1> {
        RegisterAddress::new(self.0 + 0x14)
    }
    pub fn PS_COMMON_CFG(&self) -> RegisterAddress<ps_common::PS_COMMON_CFG> {
        RegisterAddress::new(self.0 + 0x4)
    }
    pub fn SFLOW_CFG(&self) -> RegisterAddress<ps_common::SFLOW_CFG> {
        RegisterAddress::new(self.0 + 0x8)
    }
    pub fn SFLOW_RESET_CTRL(&self) -> RegisterAddress<ps_common::SFLOW_RESET_CTRL> {
        RegisterAddress::new(self.0 + 0xc)
    }
    pub fn STACK_A_CFG(&self) -> RegisterAddress<ps_common::STACK_A_CFG> {
        RegisterAddress::new(self.0 + 0x20)
    }
    pub fn STACK_A_CFG1(&self) -> RegisterAddress<ps_common::STACK_A_CFG1> {
        RegisterAddress::new(self.0 + 0x24)
    }
    pub fn STACK_CFG(&self) -> RegisterAddress<ps_common::STACK_CFG> {
        RegisterAddress::new(self.0 + 0x18)
    }
    pub fn STACK_CFG1(&self) -> RegisterAddress<ps_common::STACK_CFG1> {
        RegisterAddress::new(self.0 + 0x1c)
    }
    pub fn VSTAX_CTRL(&self, index: u32) -> RegisterAddress<ps_common::VSTAX_CTRL> {
        assert!(index < 53);
        RegisterAddress::new(self.0 + 0x30 + index * 0x4)
    }
    pub fn VSTAX_GMIRROR_CFG(&self) -> RegisterAddress<ps_common::VSTAX_GMIRROR_CFG> {
        RegisterAddress::new(self.0 + 0x104)
    }
    pub fn VSTAX_GMIRROR_CFG1(&self) -> RegisterAddress<ps_common::VSTAX_GMIRROR_CFG1> {
        RegisterAddress::new(self.0 + 0x108)
    }
}

/// Diagnostic information
pub struct PS_STICKY(pub(super) u32);
impl PS_STICKY {
    pub fn PGID_MISC_CFG(&self) -> RegisterAddress<ps_sticky::PGID_MISC_CFG> {
        RegisterAddress::new(self.0 + 0x8)
    }
}

/// Counter configuration for diagnostic information
pub struct PS_STICKY_MASK(pub(super) u32);
impl PS_STICKY_MASK {
    pub fn STICKY(&self) -> RegisterAddress<ps_sticky_mask::STICKY> {
        RegisterAddress::new(self.0 + 0x0)
    }
}

/// Access core memory
pub struct RAM_CTRL(pub(super) u32);
impl RAM_CTRL {
}

/// sFlow sampler configuration & status per port
pub struct SFLOW(pub(super) u32);
impl SFLOW {
    pub fn SFLOW_CTRL(&self) -> RegisterAddress<sflow::SFLOW_CTRL> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn SRC_CFG1(&self) -> RegisterAddress<sflow::SRC_CFG1> {
        RegisterAddress::new(self.0 + 0x4)
    }
}

/// Source port masks
pub struct SRC(pub(super) u32);
impl SRC {
    pub fn AGGR_CFG1(&self) -> RegisterAddress<src::AGGR_CFG1> {
        RegisterAddress::new(self.0 + 0x4)
    }
    pub fn SRC_CFG(&self) -> RegisterAddress<src::SRC_CFG> {
        RegisterAddress::new(self.0 + 0x0)
    }
}

/// Individual configuration.
pub struct STAT_CNT_CFG_ACL(pub(super) u32);
impl STAT_CNT_CFG_ACL {
    pub fn STAT_GLOBAL_EVENT_MASK(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_acl::STAT_GLOBAL_EVENT_MASK> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x10 + index * 0x4)
    }
    pub fn STAT_LSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_acl::STAT_LSB_CNT> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
}

/// Individual configuration.
pub struct STAT_CNT_CFG_BDLB(pub(super) u32);
impl STAT_CNT_CFG_BDLB {
    pub fn STAT_GLOBAL_EVENT_MASK(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_bdlb::STAT_GLOBAL_EVENT_MASK> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x10 + index * 0x4)
    }
    pub fn STAT_LSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_bdlb::STAT_LSB_CNT> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
}

/// Individual configuration.
pub struct STAT_CNT_CFG_BUM(pub(super) u32);
impl STAT_CNT_CFG_BUM {
    pub fn STAT_GLOBAL_EVENT_MASK(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_bum::STAT_GLOBAL_EVENT_MASK> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x30 + index * 0x4)
    }
    pub fn STAT_LSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_bum::STAT_LSB_CNT> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
}

/// Individual configuration.
pub struct STAT_CNT_CFG_ERLEG(pub(super) u32);
impl STAT_CNT_CFG_ERLEG {
    pub fn STAT_GLOBAL_EVENT_MASK(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_erleg::STAT_GLOBAL_EVENT_MASK> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x40 + index * 0x4)
    }
    pub fn STAT_LSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_erleg::STAT_LSB_CNT> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STAT_MSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_erleg::STAT_MSB_CNT> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x20 + index * 0x4)
    }
}

/// Individual configuration.
pub struct STAT_CNT_CFG_IRLEG(pub(super) u32);
impl STAT_CNT_CFG_IRLEG {
    pub fn STAT_GLOBAL_EVENT_MASK(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_irleg::STAT_GLOBAL_EVENT_MASK> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x40 + index * 0x4)
    }
    pub fn STAT_LSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_irleg::STAT_LSB_CNT> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
}

/// Individual configuration.
pub struct STAT_CNT_CFG_ISDX(pub(super) u32);
impl STAT_CNT_CFG_ISDX {
    pub fn STAT_GLOBAL_EVENT_MASK(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_isdx::STAT_GLOBAL_EVENT_MASK> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x30 + index * 0x4)
    }
    pub fn STAT_LSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_isdx::STAT_LSB_CNT> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
}

/// Individual configuration.
pub struct STAT_CNT_CFG_PORT(pub(super) u32);
impl STAT_CNT_CFG_PORT {
    pub fn STAT_CFG(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_port::STAT_CFG> {
        assert!(index < 4);
        RegisterAddress::new(self.0 + 0x4 + index * 0x4)
    }
    pub fn STAT_EVENTS_STICKY(&self) -> RegisterAddress<stat_cnt_cfg_port::STAT_EVENTS_STICKY> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn STAT_LSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_port::STAT_LSB_CNT> {
        assert!(index < 4);
        RegisterAddress::new(self.0 + 0x14 + index * 0x4)
    }
    pub fn STAT_RESET(&self) -> RegisterAddress<stat_cnt_cfg_port::STAT_RESET> {
        RegisterAddress::new(self.0 + 0x10)
    }
}

/// Individual configuration.
pub struct STAT_CNT_CFG_QUEUE(pub(super) u32);
impl STAT_CNT_CFG_QUEUE {
    pub fn STAT_GLOBAL_EVENT_MASK(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_queue::STAT_GLOBAL_EVENT_MASK> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x10 + index * 0x4)
    }
    pub fn STAT_LSB_CNT(&self, index: u32) -> RegisterAddress<stat_cnt_cfg_queue::STAT_LSB_CNT> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
}

/// Common counter configuration.
pub struct STAT_GLOBAL_CFG_ACL(pub(super) u32);
impl STAT_GLOBAL_CFG_ACL {
    pub fn GLOBAL_CNT_FRM_TYPE_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_acl::GLOBAL_CNT_FRM_TYPE_CFG> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STAT_GLOBAL_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_acl::STAT_GLOBAL_CFG> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x8 + index * 0x4)
    }
    pub fn STAT_MSB_CNT(&self, index: u32) -> RegisterAddress<stat_global_cfg_acl::STAT_MSB_CNT> {
        assert!(index < 4);
        RegisterAddress::new(self.0 + 0x24 + index * 0x4)
    }
}

/// Common counter configuration.
pub struct STAT_GLOBAL_CFG_BDLB(pub(super) u32);
impl STAT_GLOBAL_CFG_BDLB {
    pub fn GLOBAL_CNT_FRM_TYPE_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_bdlb::GLOBAL_CNT_FRM_TYPE_CFG> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STAT_GLOBAL_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_bdlb::STAT_GLOBAL_CFG> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x8 + index * 0x4)
    }
    pub fn STAT_MSB_CNT(&self, index: u32) -> RegisterAddress<stat_global_cfg_bdlb::STAT_MSB_CNT> {
        assert!(index < 3);
        RegisterAddress::new(self.0 + 0x18 + index * 0x4)
    }
}

/// Common counter configuration.
pub struct STAT_GLOBAL_CFG_BUM(pub(super) u32);
impl STAT_GLOBAL_CFG_BUM {
    pub fn GLOBAL_CNT_FRM_TYPE_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_bum::GLOBAL_CNT_FRM_TYPE_CFG> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STAT_GLOBAL_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_bum::STAT_GLOBAL_CFG> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x18 + index * 0x4)
    }
    pub fn STAT_MSB_CNT(&self, index: u32) -> RegisterAddress<stat_global_cfg_bum::STAT_MSB_CNT> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x8 + index * 0x4)
    }
}

/// Common counter configuration.
pub struct STAT_GLOBAL_CFG_ERLEG(pub(super) u32);
impl STAT_GLOBAL_CFG_ERLEG {
    pub fn GLOBAL_CNT_FRM_TYPE_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_erleg::GLOBAL_CNT_FRM_TYPE_CFG> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STAT_GLOBAL_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_erleg::STAT_GLOBAL_CFG> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x20 + index * 0x4)
    }
    pub fn STAT_MSB_CNT(&self, index: u32) -> RegisterAddress<stat_global_cfg_erleg::STAT_MSB_CNT> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x20 + index * 0x4)
    }
}

/// Common counter configuration.
pub struct STAT_GLOBAL_CFG_IRLEG(pub(super) u32);
impl STAT_GLOBAL_CFG_IRLEG {
    pub fn GLOBAL_CNT_FRM_TYPE_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_irleg::GLOBAL_CNT_FRM_TYPE_CFG> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STAT_GLOBAL_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_irleg::STAT_GLOBAL_CFG> {
        assert!(index < 8);
        RegisterAddress::new(self.0 + 0x20 + index * 0x4)
    }
    pub fn STAT_MSB_CNT(&self, index: u32) -> RegisterAddress<stat_global_cfg_irleg::STAT_MSB_CNT> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x18 + index * 0x4)
    }
}

/// Common counter configuration.
pub struct STAT_GLOBAL_CFG_ISDX(pub(super) u32);
impl STAT_GLOBAL_CFG_ISDX {
    pub fn GLOBAL_CNT_FRM_TYPE_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_isdx::GLOBAL_CNT_FRM_TYPE_CFG> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STAT_GLOBAL_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_isdx::STAT_GLOBAL_CFG> {
        assert!(index < 6);
        RegisterAddress::new(self.0 + 0x18 + index * 0x4)
    }
    pub fn STAT_MSB_CNT(&self, index: u32) -> RegisterAddress<stat_global_cfg_isdx::STAT_MSB_CNT> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x8 + index * 0x4)
    }
}

/// Common counter configuration.
pub struct STAT_GLOBAL_CFG_PORT(pub(super) u32);
impl STAT_GLOBAL_CFG_PORT {
    pub fn STAT_GLOBAL_EVENT_MASK(&self, index: u32) -> RegisterAddress<stat_global_cfg_port::STAT_GLOBAL_EVENT_MASK> {
        assert!(index < 4);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STICKY_MASK(&self) -> RegisterAddress<stat_global_cfg_port::STICKY_MASK> {
        RegisterAddress::new(self.0 + 0x0)
    }
}

/// Common counter configuration.
pub struct STAT_GLOBAL_CFG_QUEUE(pub(super) u32);
impl STAT_GLOBAL_CFG_QUEUE {
    pub fn GLOBAL_CNT_FRM_TYPE_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_queue::GLOBAL_CNT_FRM_TYPE_CFG> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    pub fn STAT_GLOBAL_CFG(&self, index: u32) -> RegisterAddress<stat_global_cfg_queue::STAT_GLOBAL_CFG> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x8 + index * 0x4)
    }
    pub fn STAT_MSB_CNT(&self, index: u32) -> RegisterAddress<stat_global_cfg_queue::STAT_MSB_CNT> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x8 + index * 0x4)
    }
}

/// UPSID table (one entry per UPS)
pub struct UPSID(pub(super) u32);
impl UPSID {
    pub fn SFLOW_CNT(&self) -> RegisterAddress<upsid::SFLOW_CNT> {
        RegisterAddress::new(self.0 + 0x4)
    }
    pub fn STACK_LINK_EQUAL_COST_CFG(&self) -> RegisterAddress<upsid::STACK_LINK_EQUAL_COST_CFG> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn UPSID_CFG(&self) -> RegisterAddress<upsid::UPSID_CFG> {
        RegisterAddress::new(self.0 + 0x4)
    }
}
