// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Based on mesa-v2021.09 (https://github.com/microchip-ung/mesa/) which has
// the following copyright and license:
//
// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This is an autogenerated file; do not edit by hand!

use crate::types::RegisterAddress;

// Register groups are stored in the tree as submodules

pub mod inj;
pub mod xtr;

/// Frame injection
pub struct INJ(pub(super) u32);
impl INJ {
    #[inline]
    pub fn INJ_CTRL(&self, index: u32) -> RegisterAddress<inj::INJ_CTRL> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x10 + index * 0x4)
    }
    #[inline]
    pub fn INJ_ERR(&self, index: u32) -> RegisterAddress<inj::INJ_ERR> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x1c + index * 0x4)
    }
    #[inline]
    pub fn INJ_GRP_CFG(&self, index: u32) -> RegisterAddress<inj::INJ_GRP_CFG> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    #[inline]
    pub fn INJ_STATUS(&self) -> RegisterAddress<inj::INJ_STATUS> {
        RegisterAddress::new(self.0 + 0x18)
    }
    #[inline]
    pub fn INJ_WR(&self, index: u32) -> RegisterAddress<inj::INJ_WR> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x8 + index * 0x4)
    }
    #[inline]
    pub fn VTSS_DBG(&self) -> RegisterAddress<inj::VTSS_DBG> {
        RegisterAddress::new(self.0 + 0x24)
    }
}

/// Frame extraction
pub struct XTR(pub(super) u32);
impl XTR {
    #[inline]
    pub fn XTR_CFG(&self) -> RegisterAddress<xtr::XTR_CFG> {
        RegisterAddress::new(self.0 + 0x20)
    }
    #[inline]
    pub fn XTR_DATA_PRESENT(&self) -> RegisterAddress<xtr::XTR_DATA_PRESENT> {
        RegisterAddress::new(self.0 + 0x1c)
    }
    #[inline]
    pub fn XTR_FLUSH(&self) -> RegisterAddress<xtr::XTR_FLUSH> {
        RegisterAddress::new(self.0 + 0x18)
    }
    #[inline]
    pub fn XTR_FRM_PRUNING(&self, index: u32) -> RegisterAddress<xtr::XTR_FRM_PRUNING> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x10 + index * 0x4)
    }
    #[inline]
    pub fn XTR_GRP_CFG(&self, index: u32) -> RegisterAddress<xtr::XTR_GRP_CFG> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
    #[inline]
    pub fn XTR_RD(&self, index: u32) -> RegisterAddress<xtr::XTR_RD> {
        assert!(index < 2);
        RegisterAddress::new(self.0 + 0x8 + index * 0x4)
    }
}
