// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Based on mesa-v2021.09 (https://github.com/microchip-ung/mesa/) which has
// the following copyright and license:
//
// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This is an autogenerated file; do not edit by hand!

use crate::types::RegisterAddress;

// Register groups are stored in the tree as submodules

pub mod res_ctrl;
pub mod res_qos_adv;
pub mod res_wred;

/// Watermarks and status for egress queue system
pub struct RES_CTRL(pub(super) u32);
impl RES_CTRL {
    pub fn RES_CFG(&self) -> RegisterAddress<res_ctrl::RES_CFG> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn RES_STAT(&self) -> RegisterAddress<res_ctrl::RES_STAT> {
        RegisterAddress::new(self.0 + 0x4)
    }
    pub fn RES_STAT_CUR(&self) -> RegisterAddress<res_ctrl::RES_STAT_CUR> {
        RegisterAddress::new(self.0 + 0x8)
    }
}

/// Not documented
pub struct RES_QOS_ADV(pub(super) u32);
impl RES_QOS_ADV {
    pub fn PFC_CFG(&self, index: u32) -> RegisterAddress<res_qos_adv::PFC_CFG> {
        assert!(index < 57);
        RegisterAddress::new(self.0 + 0xe8 + index * 0x4)
    }
    pub fn RES_DLB_OFFSET(&self) -> RegisterAddress<res_qos_adv::RES_DLB_OFFSET> {
        RegisterAddress::new(self.0 + 0x1cc)
    }
    pub fn RES_QOS_MODE(&self) -> RegisterAddress<res_qos_adv::RES_QOS_MODE> {
        RegisterAddress::new(self.0 + 0xe4)
    }
    pub fn WRED_GROUP(&self, index: u32) -> RegisterAddress<res_qos_adv::WRED_GROUP> {
        assert!(index < 57);
        RegisterAddress::new(self.0 + 0x0 + index * 0x4)
    }
}

/// Not documented
pub struct RES_WRED(pub(super) u32);
impl RES_WRED {
    pub fn WRED_PROFILE(&self) -> RegisterAddress<res_wred::WRED_PROFILE> {
        RegisterAddress::new(self.0 + 0x0)
    }
}
