// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Based on mesa-v2021.09 (https://github.com/microchip-ung/mesa/) which has
// the following copyright and license:
//
// Copyright (c) 2004-2021 Microchip Technology Inc. and its subsidiaries.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This is an autogenerated file; do not edit by hand!

use crate::types::RegisterAddress;

// Register groups are stored in the tree as submodules

pub mod xfi_control;

/// XFI controls
pub struct XFI_CONTROL(pub(super) u32);
impl XFI_CONTROL {
    pub fn DATA_VALID_DETECT_CTRL(&self) -> RegisterAddress<xfi_control::DATA_VALID_DETECT_CTRL> {
        RegisterAddress::new(self.0 + 0x24)
    }
    pub fn HSS_MASK(&self) -> RegisterAddress<xfi_control::HSS_MASK> {
        RegisterAddress::new(self.0 + 0x1c)
    }
    pub fn HSS_STATUS(&self) -> RegisterAddress<xfi_control::HSS_STATUS> {
        RegisterAddress::new(self.0 + 0x20)
    }
    pub fn HSS_STICKY(&self) -> RegisterAddress<xfi_control::HSS_STICKY> {
        RegisterAddress::new(self.0 + 0x18)
    }
    pub fn INT_CTRL(&self) -> RegisterAddress<xfi_control::INT_CTRL> {
        RegisterAddress::new(self.0 + 0xc)
    }
    pub fn KR_CONTROL(&self) -> RegisterAddress<xfi_control::KR_CONTROL> {
        RegisterAddress::new(self.0 + 0x0)
    }
    pub fn SSF_HYST_ENA_CTRL(&self) -> RegisterAddress<xfi_control::SSF_HYST_ENA_CTRL> {
        RegisterAddress::new(self.0 + 0x10)
    }
    pub fn SSF_HYST_TIMING_CTRL(&self) -> RegisterAddress<xfi_control::SSF_HYST_TIMING_CTRL> {
        RegisterAddress::new(self.0 + 0x14)
    }
    pub fn XFI_MODE(&self) -> RegisterAddress<xfi_control::XFI_MODE> {
        RegisterAddress::new(self.0 + 0x4)
    }
    pub fn XFI_STATUS(&self) -> RegisterAddress<xfi_control::XFI_STATUS> {
        RegisterAddress::new(self.0 + 0x8)
    }
}
